# -*- mode: python ; coding: utf-8 -*-

from pathlib import Path

block_cipher = None
project_root = Path(SPECPATH)

a = Analysis(
    ["launcher.py"],
    pathex=[str(project_root)],
    binaries=[],
    datas=[
        (str(project_root / "frontend" / "dist"), "frontend/dist"),
    ],
    hiddenimports=[
        "backend",
        "backend.main",
        "backend.core.config",
        "backend.core.runtime_paths",
        "backend.core.ee_client",
        "backend.core.leyenda",
        "backend.core.biomas",
        "backend.core.versiones_col4",
        "backend.core.cache",
        "backend.core.sheets_client",
        "backend.core.paths",
        "backend.routers.mapbiomas",
        "backend.routers.landsat",
        "backend.routers.stats",
        "backend.routers.puntos",
        "backend.services.comparacion_service",
        "backend.services.landsat_service",
        "backend.services.stats_service",
        "backend.services.region_bounds_service",
        "backend.services.asignacion_excel",
        "backend.services.puntos_storage",
        "backend.models.registro",
        "backend.db.session",
        "backend.db.models",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.h11_impl",
        "uvicorn.protocols.http.httptools_impl",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "uvicorn.lifespan.off",
        "uvicorn.importer",
        "sqlalchemy.dialects.sqlite",
        "openpyxl",
        "ee",
        "google.auth",
        "google.oauth2",
        "googleapiclient",
        "gspread",
        "multipart",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "torch",
        "torchvision",
        "tensorflow",
        "matplotlib",
        "IPython",
        "jupyter",
        "notebook",
        "pytest",
        "tkinter",
        "_tkinter",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Validation_TEAM",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Validation_TEAM",
)
